version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_webapp
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: bash -c "npm install && npm run dev"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password  # Replace with your root password
    depends_on:
      - mysql

volumes:
  dbdata:

